COMMON_OBJS := Graph Edge Parser ProblemInstance Timer DijkstraSolution Dijkstra
OBJS := InitialSolution Solution NeighbourhoodSelector LocalHeuristic HeuristicFactory NeighbourhoodSelectorA NeighbourhoodSelectorB NeighbourhoodSelectorC InitialSolutionA InitialSolutionB InitialSolutionC
include ../Makefile.common
