COMMON_OBJS := Node Graph Edge Parser ProblemInstance DijkstraSolution Dijkstra UnvisitedNode Timer Solution ObjectiveFunctions
OBJS := local_search NeighbourhoodSelector NeighbourhoodSelectorA InitialSolution
include ../Makefile.common
