COMMON_OBJS := Graph Edge Parser ProblemInstance Timer DijkstraSolution Dijkstra
OBJS := InitialSolution Solution NeighbourhoodSelector LocalHeuristic HeuristicFactory local_search NeighbourhoodSelectorA NeighbourhoodSelectorB NeighbourhoodSelectorC InitialSolutionA InitialSolutionB InitialSolutionC
include ../Makefile.common
