COMMON_OBJS := Graph Edge Parser ProblemInstance Timer DijkstraSolution Dijkstra DijkstraRandomized UnvisitedNode Solution
OBJS := grasp NeighbourhoodSelector NeighbourhoodSelectorA InitialSolution
include ../Makefile.common
